import importlib.util
import io
import os
import tarfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "import_google_web_assets.py"


def load_import_script():
    spec = importlib.util.spec_from_file_location("import_google_web_assets", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


def add_tar_text(tar: tarfile.TarFile, name: str, text: str) -> None:
    data = text.encode("utf-8")
    info = tarfile.TarInfo(name)
    info.size = len(data)
    tar.addfile(info, fileobj=io.BytesIO(data))


def add_tar_bytes(tar: tarfile.TarFile, name: str, data: bytes) -> None:
    info = tarfile.TarInfo(name)
    info.size = len(data)
    tar.addfile(info, fileobj=io.BytesIO(data))


def make_noto_archive(path: Path) -> None:
    with tarfile.open(path, "w:gz") as tar:
        for weight in ("400", "500", "600", "700"):
            add_tar_text(
                tar,
                f"package/chinese-simplified-{weight}.css",
                (
                    "@font-face {\n"
                    "  font-family: 'Noto Sans SC';\n"
                    f"  font-weight: {weight};\n"
                    f"  src: url('./files/noto-sans-sc-{weight}.woff2') format('woff2');\n"
                    "}\n"
                ),
            )
            add_tar_bytes(
                tar,
                f"package/files/noto-sans-sc-{weight}.woff2",
                f"noto-{weight}".encode(),
            )


def test_targeted_noto_import_does_not_touch_material_symbols(tmp_path, monkeypatch):
    module = load_import_script()

    static_font_dir = tmp_path / "static" / "fonts" / "google"
    vendor_dir = tmp_path / "static" / "vendor"
    design_asset_dir = tmp_path / "design"
    design_font_dir = design_asset_dir / "fonts" / "google"
    design_vendor_dir = design_asset_dir / "vendor"
    icon_dir = tmp_path / "static" / "icons" / "material-design"
    design_icon_dir = design_asset_dir / "icons" / "material-design"

    for directory in (static_font_dir, vendor_dir, design_font_dir, design_vendor_dir):
        directory.mkdir(parents=True)

    material_font = static_font_dir / "material-symbols-outlined.woff2"
    design_material_font = design_font_dir / "material-symbols-outlined.woff2"
    material_font.write_bytes(b"existing-material")
    design_material_font.write_bytes(b"design-material-different")
    old_time = 1_700_000_000
    os.utime(material_font, (old_time, old_time))
    os.utime(design_material_font, (old_time, old_time))

    (vendor_dir / "google-fonts.css").write_text(
        "/* Generated by scripts/import_google_web_assets.py. Do not edit by hand. */\n\n"
        "/* @fontsource/inter */\n\n"
        "@font-face { font-family: 'Inter'; src: url('/vizo/static/fonts/google/inter.woff2'); }\n",
        encoding="utf-8",
    )
    (vendor_dir / "material-symbols.css").write_text(
        "/* material symbols */\n",
        encoding="utf-8",
    )

    archive = tmp_path / "fontsource-noto-sans-sc.tgz"
    make_noto_archive(archive)

    def fake_npm_pack(package: str, destination: Path) -> Path:
        assert package == "@fontsource/noto-sans-sc"
        return archive

    monkeypatch.setattr(module, "FONT_DIR", static_font_dir)
    monkeypatch.setattr(module, "VENDOR_DIR", vendor_dir)
    monkeypatch.setattr(module, "ICON_DIR", icon_dir)
    monkeypatch.setattr(module, "DESIGN_ASSET_DIR", design_asset_dir)
    monkeypatch.setattr(module, "DESIGN_FONT_DIR", design_font_dir)
    monkeypatch.setattr(module, "DESIGN_VENDOR_DIR", design_vendor_dir)
    monkeypatch.setattr(module, "DESIGN_ICON_DIR", design_icon_dir)
    monkeypatch.setattr(module, "npm_pack", fake_npm_pack)

    module.main(["--font-family", "noto-sans-sc", "--skip-svg-icons"])

    assert material_font.read_bytes() == b"existing-material"
    assert design_material_font.read_bytes() == b"design-material-different"
    assert material_font.stat().st_mtime == old_time
    assert design_material_font.stat().st_mtime == old_time
    assert (
        static_font_dir / "noto-sans-sc-noto-sans-sc-400.woff2"
    ).read_bytes() == b"noto-400"

    google_css = (vendor_dir / "google-fonts.css").read_text(encoding="utf-8")
    assert "/* @fontsource/inter */" in google_css
    assert "/* @fontsource/noto-sans-sc */" in google_css
